/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExForm: typeof import('ex-plus/index')['ExForm']
    ExFormItem: typeof import('ex-plus/index')['ExFormItem']
    ExInput: typeof import('ex-plus/index')['ExInput']
  }
}
export {}
